Ein '''Quantenprozessor''' bzw. '''Quantencomputer''' ist ein [[Prozessor]], dessen Funktion auf den Gesetzen der [[Quantenmechanik]] beruht.

Im Unterschied zum [[Digitalrechner]] arbeitet er nicht auf der Basis der Gesetze der [[Klassische Physik|klassischen Physik]] bzw. [[Informatik]], sondern auf der Basis [[Qubit|quantenmechanischer Zustände]]. Die Verarbeitung dieser Zustände erfolgt nach quantenmechanischen Prinzipien. Hierbei sind (i) das [[Superposition (Physik)|Superpositionsprinzip]] (d.&nbsp;h. die quantenmechanische [[Kohärenz (Physik)|Kohärenz]], analog zu den Kohärenzeffekten, siehe z.&nbsp;B. [[Holographie]], in der sonst inkohärenten [[Optik]]) und (ii) die [[Quantenverschränkung]] von Bedeutung.
Theoretische Studien zeigen, dass unter Ausnutzung dieser Effekte bestimmte Probleme der Informatik, z.&nbsp;B. die Suche in extrem großen [[Datenbank]]en (siehe [[Grover-Algorithmus]]) und die [[Faktorisierungsverfahren|Faktorisierung]] großer Zahlen (siehe [[Shor-Algorithmus]]) effizienter gelöst werden können als mit klassischen Computern. Dies würde viele mathematische Probleme leichter lösbar machen.

Der Quantencomputer war lange ein überwiegend theoretisches Konzept. Es gibt verschiedene Vorschläge, wie ein Quantencomputer realisiert werden könnte, und in kleinem Maßstab wurden einige dieser Konzepte im Labor erprobt und Quantencomputer mit wenigen [[Qubit]]s realisiert. Neben der Anzahl der Qubits ist aber auch zum Beispiel eine geringe Fehlerquote beim Rechnen und Auslesen wichtig und wie lange die Zustände in den Qubits aufrechterhalten werden können. Gegenwärtig (2018) investieren viele große Computerfirmen in die Entwicklung von Quantencomputern und der Rekord liegt bei rund 50 bis 70 Qubits.

== Qubits ==
{{Hauptartikel|Qubit}}
[[Datei:Simple qubits.svg|mini|Zur Definition des Begriffes [[Qubit]]:<br /> Beim Quantencomputing arbeitet man mit allgemeinen Zuständen, die in bestimmter Weise durch ''Überlagerung''&nbsp; der beiden farbig gekennzeichneten Basiszustände entstehen, wogegen beim klassischen Computing nur die Basiszustände selbst auftreten.]]
In einem klassischen Computer wird sämtliche Information in [[Bit]]s dargestellt. Physikalisch wird ein Bit dadurch realisiert, dass ein Spannungspotential entweder oberhalb eines bestimmten Pegels liegt oder unterhalb.

Auch in einem Quantencomputer wird Information in der Regel [[Dualsystem|binär]] dargestellt. Dazu bedient man sich eines physikalischen Systems mit zwei nicht notwendigerweise orthogonal gewählten [[Quantenmechanischer Zustand|Basiszuständen]] eines zweidimensionalen [[Komplexe Zahl|komplexen]] Raums, wie er in der Quantenmechanik auftritt. Ein Basiszustand repräsentiert den quantenmechanischen Zustandsvektor <math>|0\rangle</math>, der andere den Zustandsvektor <math>| 1\rangle</math>. Dabei wird die [[Dirac-Notation]] genutzt. Bei diesen quantenmechanischen Zwei-Niveau-Systemen kann es sich z.&nbsp;B. um den [[Spin]] eines [[Elektron]]s handeln, der entweder nach oben oder z.&nbsp;B. nach vorn zeigt. Andere Implementierungen nutzen das [[Energieniveau]] in [[Atom]]en oder [[Molekül]]en oder die Flussrichtung eines [[Elektrischer Strom|Stroms]] in einem ringförmigen [[Supraleiter]]. Ein solches quantenmechanisches [[Zweizustandssystem]] wird [[Qubit]] (''Quanten-Bit'') genannt.

Eine Eigenschaft quantenmechanischer Zustandsvektoren ist, dass diese eine Überlagerung anderer Zustände sein können. Dies wird auch Superposition genannt. Im konkreten Fall bedeutet dies, dass ein Qubit nicht ''entweder'' <math>|0\rangle</math> ''oder'' <math>|1\rangle</math> sein muss, wie dies für die Bits des klassischen Computers der Fall ist. Vielmehr ergibt sich der Zustand eines Qubits in dem oben erwähnten zweidimensionalen komplexen Raum allgemein zu

:<math>\vert\Psi\rangle = c_0 \vert 0\rangle + c_1 \vert 1\rangle</math>,

wobei wie in der kohärenten Optik beliebige Überlagerungszustände zugelassen sind. Der Unterschied zwischen klassischem und quantenmechanischem Computing ist also analog dem zwischen [[Kohärenz (Physik)|inkohärenter bzw. kohärenter]] Optik (im ersten Fall werden Intensitäten addiert, im zweiten direkt die Feldamplituden, wie etwa in der [[Holographie]]).

Hierbei sind <math>c_0</math> und <math>c_1</math> [[komplexe Zahl]]en.
Zur [[Norm (Mathematik)|Normierung]] fordert man <math> |c_0|^2+|c_1|^2 + 2\cdot \Re \{c_0^*\cdot c_1\,\langle 0\vert 1 \rangle \} = 1</math>.
Ohne Beschränkung der Allgemeinheit kann <math>c_0</math> reell und nichtnegativ gewählt werden.
Die [[Wahrscheinlichkeit]] dafür, als Resultat einer Messung am Zustand <math>\vert\Psi\rangle</math> den Wert 0 zu erhalten, beträgt
<math>P(0) = |\langle 0\vert\Psi\rangle|^2 =|c_0 + c_1 \langle 0\vert 1 \rangle|^2</math>.
Die [[Wahrscheinlichkeit]] dafür, als Resultat einer im Allgemeinen anderen Messung am Zustand <math>\vert\Psi\rangle</math> den Wert 1 zu erhalten, beträgt
<math>P(1) = |\langle 1\vert\Psi\rangle|^2 =|c_0 \langle 1\vert 0 \rangle + c_1|^2</math>. Die Summe <math>P(0)+P(1)</math> ist nur für orthogonale Basiszustände 1.
Davon unabhängig darf dieses probabilistische Verhalten nicht so interpretiert werden, dass sich das Qubit mit einer bestimmten Wahrscheinlichkeit im Zustand <math>\vert 0\rangle</math> und mit einer anderen Wahrscheinlichkeit im Zustand <math>\left\vert 1\right\rangle</math> befindet, während andere Zustände nicht zugelassen sind. Ein solches ausschließendes Verhalten könnte man auch mit einem klassischen Computer erzielen, der einen Zufallsgenerator verwendet, um beim Auftreten von überlagerten Zuständen zu entscheiden, ob er mit 0 oder 1 weiterrechnet. Ein solches ausschließendes Verhalten kommt in der [[Statistische Physik|statistischen Physik]] vor, die im Gegensatz zur Quantenmechanik inkohärent ist.

Bei Berücksichtigung der kohärenten Überlagerung erhält man allgemein
:<math>P(\Psi) := |\Psi|^2 = |c_0|^2+|c_1|^2 + 2\cdot \Re \{c_0^*\cdot c_1\,\langle 0\vert 1 \rangle \}</math>,

wobei <math>\Re\{c\} = \operatorname{Re}(c)</math> den [[Realteil]] der komplexen Zahl <math>c</math> bedeutet, <math>c_0^*</math> die [[Konjugation (Mathematik)|konjugiert-komplexe Zahl]] zu <math>c_0</math> und <math>\langle 0\vert 1\rangle</math> das quantenmechanische [[Skalarprodukt]] der betreffenden Zustände ist.<ref>Die Formel entspricht der Verallgemeinerung der Regel <math>(a+b)^2 = a^2+b^2+2ab</math>.</ref>

== Quantenregister, Verschränkung ==
Wie beim klassischen Computer fasst man mehrere Qubits zu Quantenregistern zusammen. Der Zustand eines Qubit-Registers ist dann gemäß den Gesetzen der Vielteilchen-Quantenmechanik ein Zustand aus einem <math>2^N</math>-dimensionalen [[Hilbert-Raum]]. Eine mögliche [[Basis (Vektorraum)|Basis]] dieses Vektorraums ist die Produktbasis über der Basis <math>\vert 0\rangle, \vert 1\rangle</math>. Für ein Register aus zwei Qubits erhielte man demnach die Basis <math>\vert 00\rangle, \vert 01\rangle, \vert 10\rangle, \vert 11\rangle</math>. Auch der Zustand des Registers kann eine beliebige Superposition dieser Basiszustände sein, also bei <math>N</math> Qubits von der Form
:<math>\Psi :=\sum_{i_1,\dots,i_N}c_{i_1\dots i_N}\,\left(\vert i_1\rangle \vert i_2\rangle\dots \vert i_N\rangle \right)</math>,
mit beliebigen komplexen Zahlen <math>c_{i_1\dots i_N}</math> und der üblichen [[Dualsystem|Dualbasis]]. Auch Summen bzw. Differenzen solcher Terme sind erlaubt, während bei klassischen Computern nur die Basiszustände selbst vorkommen, d.&nbsp;h. nur aus den Ziffern 0 bzw. 1 zusammengesetzte Vorfaktoren.

Die Zustände eines Quantenregisters lassen sich nicht immer aus den Zuständen unabhängiger Qubits zusammensetzen: Beispielsweise kann der Zustand
:<math>\Psi := \frac{1}{\sqrt{2}} \left(\vert 01\rangle + \vert 10\rangle\right)</math>
''nicht'' in ein Produkt aus einem Zustand für das erste und einem Zustand für das zweite Qubit zerlegt werden.

Man nennt einen derartigen Zustand daher auch [[Quantenverschränkung|verschränkt]] (in der englischsprachigen Literatur spricht man von ''<span lang="en">entanglement</span>''). Das Gleiche gilt für den von <math>\Psi</math> verschiedenen Zustand

:<math>\Psi^\prime := \frac{1}{\sqrt{2}} \left(\vert 01\rangle - \vert 10\rangle\right)</math>.<ref>In der Spin-Interpretation (<math>\vert 1\rangle</math> <math>\hat =\uparrow</math>, <math>\vert 0\rangle</math> <math>\hat =\downarrow</math>) haben <math>\Psi^\prime</math> bzw. <math>\Psi</math> verschiedene Symmetrie, nämlich ''Singulett-'' bzw. ''Triplett-Symmetrie''; d.&nbsp;h. der Gesamtspin ''S'' des Zweispinsystems ist für <math>\Psi^\prime</math> Null, für <math>\Psi</math> dagegen Eins.</ref>

Diese Verschränkung ist ein Grund, warum Quantencomputer effizienter als klassische Computer sein können, d.&nbsp;h. dass sie prinzipiell bestimmte Probleme schneller als klassische Computer lösen können: Um den Zustand eines klassischen <math>N</math>-Bit-Registers darzustellen, benötigt man <math>N</math> Bits an Information. Der Zustand des Quanten-Registers ist aber ein Vektor aus einem <math>2^N</math>-dimensionalen Vektorraum, so dass zu dessen Darstellung <math>2^N</math> komplexwertige Koeffizienten benötigt werden. Bei großem <math>N</math> ist die Zahl <math>2^N</math> viel größer als <math>N</math> selbst.

Das Superpositionsprinzip wird oft so dargestellt, dass ein Quantencomputer in einem Quantenregister aus <math>N</math> Qubits ''gleichzeitig'' alle <math>2^N</math> Zahlen von 0 bis <math>{2^N}-1</math> speichern könnte. Diese Vorstellung ist irreführend. Da eine am Register vorgenommene Messung stets genau einen der Basiszustände auswählt, lässt sich unter Anwendung des so genannten [[Alexander Semjonowitsch Cholewo|Holevo]]-Theorems zeigen, dass der maximale zugängliche [[Information]]sgehalt eines einzelnen unverschränkten Qubits wie im klassischen Fall genau ein Bit beträgt.<ref name="NielsenChuang2000_Holevo">M.A. Nielsen, I.L. Chuang, ''Quantum computation and quantum information'', Cambridge University Press (2000), S. 531 ff.</ref><ref name="NielsenChuang2000_SDC">Unter Ausnutzung von Verschränkung ist die Übertragung von mehr als einem Bit pro Qubit möglich. Ein Beispiel ist die [[superdichte Codierung]], welche die Übertragung von zwei klassischen Bits durch Übertragung eines Qubits erlaubt. Siehe M.A. Nielsen, I.L. Chuang, ''Quantum computation and quantum information'', Cambridge University Press (2000), S. 97.</ref>
Es ist dennoch korrekt, dass das Superpositionsprinzip eine Parallelität in den Rechnungen erlaubt, die über das hinausgeht, was in einem klassischen Parallelrechner passiert. Bei der Vorstellung einiger Quantenalgorithmen wird darauf näher eingegangen.

== Quantengatter ==
{{Hauptartikel|Quantengatter}}
Beim klassischen Computer werden durch [[Logikgatter]] (engl. ''Gates'') elementare Operationen auf den Bits durchgeführt. Mehrere Gatter werden zu einem [[Schaltnetz]] verbunden, das dann komplexe Operationen wie das Addieren zweier Binärzahlen durchführen kann. Die Gatter werden durch physikalische Bauelemente wie [[Transistor]]en realisiert und die Information als elektrisches Signal durch diese Bauelemente geleitet.

Berechnungen auf einem Quantencomputer laufen grundsätzlich anders ab: Ein Quantengatter (engl. ''Quantum Gate'') ist kein technischer Baustein, sondern stellt eine elementare physikalische Manipulation eines oder mehrerer Qubits dar. Wie genau so eine Manipulation aussieht, hängt von der tatsächlichen physikalischen Natur des Qubits ab. So lässt sich der Spin eines Elektrons durch eingestrahlte [[Magnetfeld]]er beeinflussen, der Anregungszustand eines Atoms durch [[Laser]]pulse. Obwohl also ein Quantengatter kein elektronischer Baustein, sondern eine im Verlauf der Zeit auf das Quantenregister angewendete Aktion ist, beschreibt man Quantenalgorithmen mit Hilfe von Schaltplänen, vgl. hierzu den Artikel [[Liste der Quantengatter]].

Formal ist ein Quantengatter eine [[Unitäre Abbildung|unitäre Operation]] <math>U</math>, die auf den Zustand des Quanten-Registers wirkt:

:<math>\Psi \rightarrow U\cdot \Psi.</math>

Ein Quantengatter kann daher als [[unitäre Matrix]] geschrieben werden. Ein Gatter, welches den Zustand eines Qubits umdreht (negiert), würde im Falle eines zweidimensionalen Zustandsraums der folgenden Matrix entsprechen:

:<math>U = \begin{pmatrix}0&1\\1&0\end{pmatrix}.</math>

Komplizierter zu schreiben sind Quantengatter (unitäre Matrizen), die Zwei- oder Mehr-Qubitzustände modifizieren, z.&nbsp;B. das in <math>\mathbb C^4</math> definierte CNOT-Gatter, mit der Zwei-Qubit-Zustandstabelle
<math>\vert 00\rangle\to \vert 00\rangle</math>,
<math>\vert 01\rangle\to \vert 01\rangle</math>,
<math>\vert 10\rangle\to \vert 11\rangle</math> und
<math>\vert 11\rangle\to \vert 10\rangle</math>.<ref>Es wird also der zweite der beiden Spins invertiert, wenn der erste Zustand <math>\vert 1\rangle</math> ist.</ref>
Das Ergebnis lässt sich zusätzlich bezüglich Stellenindizes <math>a</math> und <math>b</math> symmetrisieren bzw. antisymmetrisieren, etwa nach dem Schema
:<math>|ab\rangle =\frac{1}{2}\left[\left(\vert ab\rangle + \vert ba\rangle \right) + \left(\vert ab\rangle - \vert ba\rangle \right)\right]</math>,
wodurch verschränkte Zustände entstehen.

Ein Quantenschaltkreis besteht aus mehreren Quantengattern, die in fester zeitlicher Abfolge auf das Quantenregister angewendet werden. Beispiele hierfür sind die [[Quanten-Fouriertransformation]] oder der [[Shor-Algorithmus]]. Mathematisch ist ein Quantenschaltkreis auch eine unitäre Transformation, deren Matrix das Produkt der Matrizen der einzelnen Quantengatter ist.

== Einweg-Quantencomputer ==
Ein weiterer Ansatz zur Implementierung eines Quantencomputers ist der sogenannte Einweg-Quantencomputer (''one-way quantum computer'', [[Hans J. Briegel]], [[Robert Raußendorf]] 2001)<ref>Robert Raussendorf, Daniel E. Browne, Hans J. Briegel ''The one-way quantum computer – a non-network model of quantum computation'', Journal of Modern Optics, Band 49, 2002, S. 1299, {{arXiv|quant-ph/0108118}}</ref>. Dieser unterscheidet sich vom Schaltkreismodell dadurch, dass zuerst ein universeller (also vom Problem unabhängiger) verschränkter Quantenzustand generiert wird (beispielsweise ein sogenannter Clusterzustand), und die eigentliche Rechnung durch gezielte Messungen an diesem Zustand durchgeführt wird. Dabei bestimmen die Ergebnisse früherer Messungen, welche weiteren Messungen durchgeführt werden.

Anders als im Schaltkreismodell wird hier der verschränkte Quantenzustand nur als Ressource benutzt. Bei der eigentlichen Rechnung werden nur einzelne Qubits des verwendeten Zustands gemessen und klassische Rechnungen durchgeführt. Insbesondere werden dabei keine Mehr-Qubit-Operationen durchgeführt (die Herstellung des Zustands benötigt solche natürlich). Dennoch lässt sich zeigen, dass der Einweg-Quantencomputer genauso leistungsfähig ist, wie ein auf dem Schaltkreismodell beruhender Quantencomputer.

== Adiabatische Quantencomputer ==
Ein weiterer Ansatz für Quantencomputer beruht auf einem anderen Konzept<ref>Edward Farhi, Jeffrey Goldstone, Sam Gutmann, Michael Sipser: ''Quantum Computation by Adiabatic Evolution'', Preprint 2000, {{arXiv|quant-ph/0001106}}</ref>: Gemäß den Gesetzen der Quantenmechanik bleibt ein quantenmechanisches System, das sich im Grundzustand (Zustand minimaler Energie) eines zeitunabhängigen Systems befindet, auch bei Veränderungen des Systems im Grundzustand, wenn die Veränderung nur hinreichend langsam (also [[Adiabatisches Theorem der Quantenmechanik|adiabatisch]]) passiert. Die Idee des adiabatischen Quantencomputers ist es, ein System zu konstruieren, das einen zu dieser Zeit noch unbekannten Grundzustand hat, der der Lösung eines bestimmten Problems entspricht, und ein anderes, dessen Grundzustand leicht experimentell zu präparieren ist. Anschließend wird das leicht zu präparierende System in das System überführt, an dessen Grundzustand man interessiert ist, und dessen Zustand dann gemessen. Wenn der Übergang langsam genug erfolgt ist, hat man so die Lösung des Problems.

Die Firma [[D-Wave Systems]] hat 2007 erklärt, einen kommerziell verwendbaren Quantencomputer entwickelt zu haben, der auf diesem Prinzip beruht.<ref>[http://www.dwavesys.com/index.php?mact=news,cntnt01,detail,0&cntnt01articleid=4&cntnt01returnid=21 D-Wave, The Quantum Computing Company]</ref>
Am 26.&nbsp;Mai 2011 verkaufte die Firma D-Wave Systems den ersten kommerziellen Quantencomputer ''D-Wave One'' an die [[Lockheed Martin]] Corporation.<ref>HPCwire: [http://www.hpcwire.com/hpcwire/2011-05-26/d-wave_sells_first_quantum_computer.html?featured=top D-Wave Sells First Quantum Computer]</ref> Ihre Ergebnisse sind allerdings noch umstritten.<ref>Robert Gast ''Ein Quantenmärchen'', Frankfurter Allgemeine Sonntagszeitung, 26. Mai 2013, S. 61, 63</ref> 2015 stellte D-Wave Systems ihre verbesserte und aufwärts skalierbare Version D-Wave-2X der Öffentlichkeit vor. Der adiabatische Quantencomputer, der speziell für die Lösung von Optimierungsproblemen entwickelt wurde, soll bei einigen Problemen bis zu 15mal schneller sein als herkömmliche klassische Spezialcomputer für die jeweiligen Probleme (beim D-Wave One war das noch nicht so). Nach Angaben von D-Wave benutzt er supraleitende Technologie und über 1.000 Qubits<ref>[https://www.dwavesys.com/press-releases/d-wave-systems-announces-general-availability-1000-qubit-d-wave-2x-quantum-computer D-Wave Systems Announces the General Availability of the 1000+ Qubit D-Wave 2X Quantum Computer], Pressemitteilung D-Wave Systems, 20. August 2015</ref> (genannt 1000+ Qubits, ausgelegt auf 1.152 Qubits), bei einer Arbeitstemperatur von 15&nbsp;mK. Unter Qubit versteht die Firma eine supraleitende Schleife auf ihrem Chip, in der die Information über die Flussrichtung codiert ist. Ein Exemplar wurde an [[Google LLC|Google]] und die [[NASA]] verkauft, die schon 2013 einen D-Wave-Computer der ersten Generation mit 512 Qubits erwarben<ref>[http://www.zeit.de/wissen/2013-06/quantencomputer-test ''Dieser Chip rechnet besser als ein Roastbeef-Sandwich''.] [[Zeit Online]], 4. Juni 2013; abgerufen am 16. Februar 2016</ref>. Google benutzt ihn, um die Vorteile von Quantum Annealing Algorithmen auszuloten, das heißt Quantenversionen von [[Simulated Annealing]].<ref>[http://googleresearch.blogspot.ca/2015/12/when-can-quantum-annealing-win.html Google Research Blog] vom 8. Dezember 2015</ref>

== Physikalische Realisierung ==
Das bisher beschriebene Konzept ist zunächst abstrakt und allgemein gültig. Will man einen konkret nutzbaren Quantencomputer bauen, muss man die natürlichen physikalischen Einschränkungen beachten, die im Folgenden beschrieben werden.

=== Relaxation ===
Überlässt man ein System sich selbst, neigt es dazu, sich ins [[thermisches Gleichgewicht|thermische Gleichgewicht]] mit seiner Umgebung zu entwickeln. Im einfachsten Fall geschieht dies über Energieaustausch mit der Umgebung, der mit Zustandsänderung der Qubits einhergeht. Dies führt dazu, dass ein Qubit aus dem Zustand <math>\vert 1\rangle</math> nach einer gewissen Zeit mit einer bestimmten Wahrscheinlichkeit in den Zustand <math>\vert 0\rangle</math> gesprungen ist und umgekehrt. Diesen Prozess nennt man [[Relaxation (Naturwissenschaft)|Relaxation]]. Als [[Relaxationszeit]] <math>T_1</math> bezeichnet man die charakteristische Zeit, in welcher sich das System (meist [[exponentiell]]) seinem stationären Zustand nähert.

=== Dekohärenz ===
Mit [[Dekohärenz]] ist der Verlust der Superpositionseigenschaften eines Quantenzustands gemeint. Durch den Einfluss der Umgebung entwickelt sich aus einem beliebigen Superpositionszustand <math>\left\lbrace c_0\vert 0\rangle + c_1\vert 1\rangle \right\rbrace</math> (wobei <math>\textstyle c_i\in\mathbb C,\ \sum_i |c_i|^2 = 1</math>) entweder der Zustand <math>\vert 0\rangle</math> oder der Zustand <math>\vert 1\rangle</math> (mit entsprechenden Wahrscheinlichkeiten, die zum Beispiel durch <math>|c_i|^2</math> gegeben sein können, während gemischte Terme (z.&nbsp;B. <math>\sim c_0^*c_1 \,</math>) ''nicht'' auftreten (Zustandsreduktion; inkohärente vs. kohärente Superposition; Thermalisierung, wie in der statistischen Physik)). Dann verhält sich das Qubit nur noch wie ein klassisches Bit. Die Dekohärenzzeit <math>T_2</math> ist in der Regel ebenfalls exponential verteilt und typischerweise kleiner als die Relaxationszeit. Während die Relaxation auch für klassische Computer ein Problem darstellt (so könnten sich Magnete auf der Festplatte spontan umpolen), ist die Dekohärenz ein rein quantenmechanisches Phänomen.

Die Verlässlichkeit von Quantencomputern kann durch die sogenannte [[Quantenfehlerkorrektur]] erhöht werden.<ref>[https://www.cond-mat.de/teaching/QCsem/smeratpaper.pdf Quantenfehlerkorrektur] (PDF; 158&nbsp;kB)</ref>

== Berechenbarkeits- und Komplexitätstheorie ==
Da formal festgelegt ist, wie ein Quantencomputer arbeitet, können die aus der [[Theoretische Informatik|theoretischen Informatik]] bekannten Begriffe wie [[Berechenbarkeit]] oder [[Komplexitätsklasse]] auch auf einen Quantencomputer übertragen werden. Man stellt dabei fest, dass ein Quantencomputer keine prinzipiell neuen Probleme lösen kann, einige Probleme allerdings schneller gelöst werden können.

=== Berechenbarkeit ===
Ein klassischer Computer kann einen Quantencomputer simulieren, da die Wirkung der Gates auf dem Quantenregister einer [[Matrix-Vektor-Multiplikation]] entspricht. Der klassische Computer muss nun einfach all diese Multiplikationen ausführen, um den Anfangs- in den Endzustand des Registers zu überführen. Die Konsequenz dieser Simulierbarkeit ist, dass alle Probleme, die auf einem Quantencomputer gelöst werden können, auch auf einem klassischen Computer gelöst werden können. Umgekehrt bedeutet dies, dass Probleme wie das [[Halteproblem]] auch auf Quantencomputern nicht gelöst werden können.

Es lässt sich zeigen, dass die Simulation eines Quantencomputers in der Komplexitätsklasse [[PSPACE]] liegt. Man geht daher davon aus, dass es keinen Simulationsalgorithmus gibt, der einen Quantencomputer mit [[polynom]]iellem Zeitverlust simuliert.

Umgekehrt kann ein Quantencomputer auch einen klassischen Computer simulieren. Dazu muss man zunächst wissen, dass jeder [[Logische Schaltung|logische Schaltkreis]] allein aus [[NAND-Gatter]]n gebildet werden kann. Mit dem [[Toffoli-Gatter]] kann man bei geeigneter Beschaltung der drei Eingänge nun ein Quantengatter erhalten, das sich auf Qubits in der Basis der klassischen Bits <math>\vert 0\rangle, \vert 1\rangle</math> wie ein NAND-Gatter verhält. Außerdem lässt sich das Toffoli-Gate dazu verwenden, ein Eingangsbit zu verdoppeln. Aufgrund des [[No-Cloning-Theorem]]s ist dies allerdings nur für die Zustände <math>\vert 0\rangle, \vert 1\rangle</math> möglich. Diese Verdopplung (auch ''Fan-out'' genannt) ist deshalb nötig, weil es bei einem klassischen Schaltkreis möglich ist, ein Bit auf zwei Leitungen zu verteilen.

=== Komplexität ===
Im Rahmen der [[Komplexitätstheorie]] ordnet man algorithmische Probleme sogenannten [[Komplexitätsklasse]]n zu. Die bekanntesten und wichtigsten Vertreter sind die Klassen [[P (Komplexitätsklasse)|P]] und [[NP (Komplexitätsklasse)|NP]]. Dabei bezeichnet P diejenigen Probleme, deren Lösung deterministisch in zur Eingabelänge polynomieller Laufzeit berechnet werden kann. In NP liegen die Probleme, zu denen es Lösungsalgorithmen gibt, die nicht-deterministisch polynomiell sind. Der Nicht-Determinismus erlaubt, gleichzeitig verschiedene Möglichkeiten abzutesten. Da unsere aktuellen Rechner deterministisch laufen, muss der Nicht-Determinismus durch Hintereinanderausführung der verschiedenen Möglichkeiten simuliert werden, wodurch die Polynomialität der Lösungsstrategie verloren gehen kann.

Für Quantencomputer definiert man die Komplexitätsklasse [[BQP]] (eingeführt 1993 durch [[Umesh Vazirani]] und [[Ethan Bernstein]]). Diese enthält diejenigen Probleme, deren Laufzeit polynomiell von der Eingabelänge abhängt und deren Fehlerwahrscheinlichkeit unter <math>\tfrac 13</math> liegt. Aus dem vorhergehenden Abschnitt folgt, dass BQP <math>\subseteq</math> PSPACE. Ferner gilt P <math>\subseteq</math> BQP, da ein Quantencomputer auch klassische Computer mit nur polynomiellem Zeitverlust simulieren kann.

Wie BQP zur wichtigen Klasse NP in Beziehung steht, ist noch unklar. Man weiß nicht, ob ein Quantencomputer ein [[NP-vollständig]]es Problem effizient lösen kann oder nicht. Könnte man nachweisen, dass BQP eine echte Teilmenge von NP ist, wäre damit auch das [[P-NP-Problem]] gelöst: Dann gälte nämlich P <math>\neq</math> NP. Andererseits würde aus dem Nachweis, dass NP echte Teilmenge von BQP ist, folgen, dass P echte Teilmenge von PSPACE ist. Sowohl das P-NP-Problem als auch die Frage P <math>\neq</math> PSPACE sind wichtige ungelöste Fragen der theoretischen Informatik.

Lange offen war, ob es Probleme gibt, die Quantencomputer beweisbar schneller und effizienter als jeder klassische Computer lösen können, anders ausgedrückt, die Teil von BQP sind, aber nicht von [[Polynomialzeithierarchie|PH]], einer Verallgemeinerung von NP. 2018 wurde ein Beispiel von  [[Ran Raz]] und [[Avishai Tal]] gefunden, das in BQP ([[Scott Aaronson]] 2009), aber nicht in PH ist (genauer bewiesen sie, dass das Problem für beide Fälle Orakel-separiert ist), das ''Forrelation''-Problem.<ref>[https://www.quantamagazine.org/finally-a-problem-that-only-quantum-computers-will-ever-be-able-to-solve-20180621/ Kevin Hartnett, Finally, a Problem That Only Quantum Computers Will Ever Be Able to Solve, Quanta Magazine], 21. Juni 2018</ref><ref>Raz, Tal: Oracle separation of BQP and PH, 2018, [https://eccc.weizmann.ac.il/report/2018/107/ Online]</ref> Gegeben sind zwei Zufallszahlengeneratoren. Das Forrelation-Problem besteht darin, aus den erzeugten Zufallszahlenfolgen herauszufinden, ob die beiden Zufallszahlgeneratoren unabhängig sind oder die Folgen doch in verborgener Weise verbunden sind, genauer ob die eine die Fouriertransformation der anderen ist. Raz und Tal bewiesen, dass Quantencomputer sehr viel weniger Hinweise (Orakel) für die Lösung benötigen als klassische Computer. Ein Quantencomputer benötigt sogar nur ein Orakel, in PH gibt es auch mit unendlich vielen Orakeln keinen Algorithmus, der das Problem löst. Das Beispiel zeigt, dass selbst für P=NP es Probleme gibt, die Quantencomputer lösen können, klassische Rechner aber nicht.

Bei anderen Problemen wie dem Faktorisierungsproblem ganzer Zahlen wird zwar vermutet, dass Quantencomputer prinzipiell schneller sind (Quantencomputer lösen es polynomialzeitlich mit dem Shor-Algorithmus), es lässt sich aber bisher nicht beweisen, da unbekannt ist, ob das Problem in der Komplexitätsklasse P liegt.

Ein anderes Problem, von dem erwartet worden war, dass es effizient von Quantencomputern gelöst werden kann, nicht aber von klassischen Computern, ist das Empfehlungsproblem (Recommendation Problem), das sogar breite praktische Anwendung hat. Betrachtet wird zum Beispiel das für Online-Dienste wichtige Problem, aus dem Abruf von Diensten oder Waren durch Nutzer Voraussagen über deren Vorlieben zu machen, was sich formalisieren lässt als Auffüllen einer Matrix, die zum Beispiel Waren den Nutzern zuordnet. 2016 gaben Iordanis Kerenidis und Anupam Prakash<ref>[https://arxiv.org/abs/1603.08675 Kerenidis, Prakash: Quantum recommendation problems], Arxiv 2016</ref> einen Quantenalgorithmus, der exponentiell schneller war als jeder damals bekannte klassische Algorithmus. 2018 gab die Studentin Ewin Tang allerdings einen klassischen Algorithmus an, der genauso schnell war.<ref>[https://www.quantamagazine.org/teenager-finds-classical-alternative-to-quantum-recommendation-algorithm-20180731/ Kevin Hartnett, Major Quantum Computing Advance Made Obsolete by Teenager], Quanta Magazine, 31. Juli 2018</ref><ref>[https://arxiv.org/abs/1807.04271 Ewin Tang, A quantum-inspired classical algorithm for recommendation systems], Arxiv 2018</ref> Tang fand den klassischen Algorithmus in Anlehnung an den Quantenalgorithmus von Kerenidis und Prakash.

== Algorithmen für Quantencomputer ==
Die bisher gefundenen [[Algorithmus|Algorithmen]] für Quantencomputer lassen sich grob in drei Kategorien einteilen:
* Algorithmen, die auf der [[Quanten-Fouriertransformation]] beruhen. Darunter fällt auch der wohl berühmteste Algorithmus für Quantencomputer, der [[Shor-Algorithmus]] zur [[Faktorisierungsverfahren|Faktorisierung]] großer Zahlen. Der Zeitaufwand ist dabei polynomiell in der Anzahl der Ziffern. Im Gegensatz dazu benötigt der beste zurzeit bekannte klassische Algorithmus, das [[Zahlkörpersieb]], superpolynomiell (aber subexponentiell) viel Zeit. Die Bedeutung von Shors Algorithmus beruht auf der Tatsache, dass die Sicherheit der asymmetrischen Verschlüsselungsverfahren wie [[RSA-Kryptosystem|RSA]] darauf basiert, dass keine hinreichend effizienten klassischen Algorithmen zur Faktorisierung großer Zahlen bekannt sind.
* Quanten-Suchalgorithmen. Hierzu gehören der [[Grover-Algorithmus]] und Varianten davon. Er dient der effizienten Suche in einem unsortierten Array. Ein gewöhnlicher Computer muss sich bei <math>n</math> Einträgen im schlimmsten Fall alle Einträge ansehen (d.&nbsp;h. vergleichen), klassisch ist dieses Problem also in [[Landau-Symbole|<math>\mathcal O(n)</math>]] Rechenschritten lösbar. Auf einem Quantencomputer kann man dies mit dem Grover-Algorithmus in lediglich <math>\mathcal O\left(\sqrt n\right)</math> Operationen erledigen. Diese Schranke ist scharf, das heißt, kein Quantenalgorithmus kann dieses Problem in ([[asymptotisch]]) weniger Operationen lösen. Daraus folgt, dass im Allgemeinen kein exponentieller Geschwindigkeitsvorteil bei Verwendung von Quantenalgorithmen zu erwarten ist.
* Quanten-Simulation. Um quantenmechanische Systeme zu simulieren, bietet es sich an, wieder quantenmechanische Systeme zu benutzen. Mit einem geeigneten Satz von Quantengattern lässt sich jeder [[Hamiltonoperator|Hamiltonian]] darstellen. Algorithmen dieser Art würden in der [[Quantenchemie]] die Simulation von Molekülen erlauben, bei denen mit heutigen Mitteln grobe Näherungen erforderlich sind.

Viele Algorithmen für Quantencomputer liefern nur mit einer gewissen Wahrscheinlichkeit ein korrektes Ergebnis; man spricht von [[Probabilistischer Algorithmus|probabilistischen Algorithmen]]. Durch wiederholtes Anwenden des Algorithmus kann die Fehlerwahrscheinlichkeit beliebig klein werden. Ist die anfängliche Erfolgswahrscheinlichkeit groß genug, reichen wenige Wiederholungen aus.

== Architektur für Quantencomputer ==
Alle bisher experimentell demonstrierten Quantencomputer bestanden aus wenigen Qubits und waren hinsichtlich Dekohärenz- und Fehlerraten sowie der verwendeten Architektur nicht [[Skalierbarkeit|skalierbar]]. Unter Architektur versteht man in diesem Kontext das Konzept zur ''skalierbaren'' Anordnung einer sehr großen Zahl von Qubits: wie kann sichergestellt werden, dass die Fehlerrate pro Gatter klein ist (unterhalb der Schwelle für [[Fehlertoleranz|fehlertolerantes Rechnen]]) und zwar unabhängig von der Zahl der Qubits des Quantencomputers und von der räumlichen Entfernung der beteiligten Qubits im Quantenregister.

Das Problem wurde von [[David DiVincenzo]] in einem Katalog von fünf Kriterien, die ein skalierbarer, fehlertoleranter Quantencomputer erfüllen muss, zusammengefasst. Die ''DiVincenzo-Kriterien'' sind<ref>{{Literatur |Autor=David P. DiVincenzo |Hrsg=[[Leo Kouwenhoven|L. Kouwenhoven]], G. Schoen und L.L. Sohn |Titel=Topics in Quantum Computers |Sammelwerk=Mesoscopic Electron Transport. NATO ASI Series E |Nummer=345 |Verlag=Kluwer Academic Publishers |Ort=Dordrecht |Datum=1997 |Seiten=657 |Sprache=en |arxiv=cond-mat/9612126v2}}</ref>

# Er besteht aus einem skalierbaren System gut charakterisierter Qubits.
# Alle Qubits können in einen wohldefinierten Anfangszustand gebracht werden (z.&nbsp;B. <math>|00\dots 0\rangle</math>).
# Ein universelles Set elementarer Quantengatter kann ausgeführt werden.
# Einzelne Qubits (zumindest eines) können ausgelesen ([[Quantenmechanische Messung|gemessen]]) werden.
# Die relevante Dekohärenzzeit ist viel länger als die Zeit, die benötigt wird, ein elementares Quantengatter zu realisieren, sodass mit geeignetem [[Quantenfehlerkorrektur|fehlerkorrigierendem Code]] die Fehlerrate pro Gatter unter der Schwelle für fehlertolerantes Quantenrechnen liegt.

Die größten Anforderungen ergeben sich aus dem ersten und dem letzten Punkt. Skalierbarkeit heißt in diesem Fall, dass es möglich sein muss, die Zahl der Qubits beliebig groß zu wählen und dass die anderen Eigenschaften unabhängig von der Zahl der Qubits erfüllt sein müssen. Die Schwelle für fehlertolerantes Rechnen liegt je nach verwendetem Code und verwendeter Geometrie des Quantenregisters bei einer Fehlerwahrscheinlichkeit von <math>10^{-4}</math> bis <math>10^{-2}</math> (oder noch kleineren Werten) pro Gatter.<ref>{{cite journal|author=A. G. Fowler ''et al.''| year=2009| title=High-threshold universal quantum computation on the surface code| journal=Phys. Rev. A| volume=80| pages=052312| doi=| arxiv=0803.0272| language=englisch}}</ref> Bisher ist kein universelles Set von Gattern mit dieser Genauigkeit realisiert worden.

Oft werden die oben genannten Kriterien um zwei weitere ergänzt, die sich auf die Vernetzung innerhalb von Quantencomputern beziehen:
# <li value="6">Eine Quanten-Schnittstelle (engl. ''quantum interface'') zwischen stationären und mobilen Qubits</li>
# Mobile Qubits können zwischen verschiedenen Orten verlässlich ausgetauscht werden.

Die Suche nach einer skalierbaren Architektur für einen fehlertoleranten Quantencomputer ist Gegenstand aktueller Forschung. Die Fragestellung ist, wie man erreichen kann, dass Quantengatter auf verschiedenen Qubits parallel (gleichzeitig) ausgeführt werden können, auch wenn die Wechselwirkung zwischen den physikalischen Qubits lokal ist, d.&nbsp;h. nicht jedes Qubit mit jedem anderen in direkter Wechselwirkung steht. Je nach verwendetem Konzept (Gatter-Netzwerk, Einweg-Quantencomputer, adiabatischer Quantencomputer, …) und der gewählten Implementierung (gefangene Ionen, supraleitende Schaltkreise, …) gibt es hierzu verschiedene Vorschläge, die bislang allenfalls für kleine Prototypen demonstriert wurden. Zu den konkretesten und weitest fortgeschrittenen Vorschlägen gehören die folgenden:

* Quantencomputer in mikrostrukturierter [[Ionenfalle]]: Qubits werden durch den internen Zustand einzelner gefangener Ionen realisiert. In einer mikrostrukturierten Falle werden die Ionen kontrolliert zwischen Speicher- und Wechselwirkungsregionen hin- und herbewegt.<ref>{{cite journal|title=Architecture for a large-scale ion-trap quantum computer| journal=Nature| volume=417| pages=709-711| date=2002-06-13| doi=10.1038/nature00784| author=D. Kielpinski, C. Monroe, and D. J. Wineland}}</ref> Anstatt die miteinander zu koppelnden Ionen in eine gemeinsame Wechselwirkungsregion zu bewegen, könnten auch langreichweitige Wechselwirkungen zwischen ihnen benutzt werden. In Experimenten an der [[Universität Innsbruck]] wurde demonstriert, dass zum Beispiel die [[Elektrischer Dipol|elektrische Dipolwechselwirkung]] zwischen kleinen Gruppen von oszillierenden Ionen (die als Antenne wirken) zur Kopplung von Ionen, die mehr als 50 Mikrometer voneinander entfernt sind, verwendet werden kann.<ref>{{cite journal|title=Trapped-ion antennae for the transmission of quantum information| author=M. Harlander ''et al.''| journal=Nature| year=2011| doi= 10.1038/nature09800| date=2011-02-23}}</ref><ref>{{Internetquelle |url=http://science.orf.at/stories/1676749/ |autor=[[ORF]]/[[Austria Presse Agentur|APA]] |titel=Quantenbytes kommunizieren per Funk |datum=2011-02-23 |zugriff=2011-02-26}}</ref>
* [[Supraleitung|Supraleitende]] Qubits in einem zweidimensionalen Netzwerk von supraleitenden [[Streifenleitung]]sresonatoren (''stripline resonators'').<ref>{{cite journal|author=F. Helmer ''et al.''| title=Cavity grid for scalable quantum computation with superconducting circuits| journal=Europhysics Letters| year=2009| volume=85| pages=50007| doi=10.1209/0295-5075/85/50007| arxiv=0706.3625}}</ref>
* Quantencomputer auf Basis von [[Stickstoff-Fehlstellen-Zentrum|Stickstoff-Fehlstellen-Zentren]] (NV-Zentren) in [[Diamant]]: Als Qubits fungieren [[Kernspin]]s von [[Stickstoff]]-Atomen in einem zweidimensionalen Gitter von NV-Zentren; Auslese und Kopplung erfolgen über den elektronischen [[Spin]] des NV-Zentrums, wobei die Kopplung durch die [[Magnetischer Dipol|magnetische Dipolwechselwirkung]] erreicht wird; inhomogene Magnetfelder ermöglichen die individuelle Adressierung und parallele Operation auf vielen Qubits.<ref>Yao ''et el.'': ''Scalable Architecture for a Room Temperature Solid-State Quantum Information Processor'', 13. Dezember 2010, {{arXiv|1012.2864}}</ref>

== Forschungsgeschichte ==
Quantencomputer mit wenigen [[Qubit]]s konnten bereits in den 1990er Jahren realisiert werden. So wurde [[Shor-Algorithmus|Shors Algorithmus]] im Jahre 2001 mit einem auf Kernspinresonanz beruhenden System am [[IBM Almaden Research Center]] mit 7&nbsp;Qubits realisiert und konnte die Zahl 15 in ihre Primfaktoren 3 und 5 zerlegen.<ref>L.M.K. Vandersypen et al.: ''Experimental realization of Shor’s factorizing algorithm using nuclear magnetic resonance''. In: ''letters to nature''. Band 414, 20./27. Dezember 2001</ref> Ebenso konnte im Jahre 2003 ein auf in [[Ionenfalle]]n gespeicherten Teilchen basierender Quantencomputer den [[Deutsch-Jozsa-Algorithmus]] realisieren.<ref>S. Gulde et al.: ''Implementation of the Deutsch-Jozsa algorithm on an ion-trap quantum computer''. In: Nature. Band 421, 2003, 48</ref>

Im November 2005 gelang es [[Rainer Blatt]] am Institut für Experimentalphysik der [[Universität Innsbruck]] erstmals, ein Quantenregister mit 8 verschränkten [[Qubit]]s zu erzeugen. Die Verschränkung aller acht Qubits musste durch 650.000 Messungen nachgewiesen werden und dauerte 10 Stunden.<ref>H. Häffner, W. Hänsel u.&nbsp;a.: ''Scalable multiparticle entanglement of trapped ions.'' In: ''Nature.'' 438, 2005, S.&nbsp;643–646, [[doi:10.1038/nature04279]].</ref>

Im März 2011 haben die Innsbrucker Wissenschaftler die Zahl der Qubits noch einmal beinahe verdoppelt. In einer Ionenfalle hielten sie 14 Calciumatome gefangen, welche sie nach dem Prinzip eines Quantenprozessors mit Laserlicht manipulierten.<ref>[http://www.uibk.ac.at/ipoint/news/2011/mit-14-quantenbits-rechnen.html.de ''Mit 14 Quantenbits rechnen''.] iPoint, 31. März 2011</ref>

An der [[Yale University]] kühlte ein Forscherteam um Leo DiCarlo ein Zwei-Qubit-Register auf einem 7&nbsp;mm langen und 2&nbsp;mm breiten, von einem mehrfach gekrümmten Kanal durchzogenen Quantenprozessor auf eine Temperatur von 13&nbsp;mK ab und erzeugte damit einen 2-Qubit-Register-Quantencomputer. Der supraleitende Chip spielte nach einer Veröffentlichung von Nature 2009 zum ersten Mal Quantenalgorithmen durch.<ref>Jürgen Rink: ''Supraleitungs-Quantenrechner''. In: ''[[c’t]]'', 2009, Heft 16, S. 52</ref><ref>L. DiCarlo, J. M. Chow u.&nbsp;a.: ''Demonstration of two-qubit algorithms with a superconducting quantum processor.'' In: ''Nature.'' 460, 2009, S.&nbsp;240, [[doi:10.1038/nature08121]]. {{arXiv|0903.2030}}</ref>

Einer Forschergruppe am [[National Institute of Standards and Technology]] (NIST) in Boulder, USA, ist es 2011 gelungen, Ionen mittels [[Mikrowellen]] zu verschränken. Die NIST-Forschergruppe hat gezeigt, dass man solche Operationen nicht nur mit einem komplexen, raumfüllenden [[Laser]]system realisieren kann, sondern auch mit miniaturisierter Mikrowellenelektronik. Um die Verschränkung zu erzeugen, integrierten die Physiker die Mikrowellenquelle in die Elektroden einer so genannten Chipfalle, einer mikroskopischen chipartigen Struktur zur Speicherung und Manipulation der Ionen in einer Vakuumzelle. Mit ihrem Experiment haben die Forscher gezeigt, dass die Verschränkung der Ionen mit Mikrowellen in 76 % aller Fälle funktioniert. Die bereits seit mehreren Jahren in der Forschung verwendeten laserbasierten Quantenlogikgatter sind mit einer Quote von 99,3 % derzeit noch besser als die Gatter auf Basis von Mikrowellen. Das neue Verfahren hat den Vorteil, dass es nur ungefähr ein Zehntel des Platzes eines Laser-Experiments beansprucht.<ref>IDW-Online: [http://idw-online.de/de/news437440 Ein wichtiger Schritt in Richtung Quantencomputer], 23. August 2011</ref><ref>C. Ospelkaus, U. Warring, Y. Colombe, K. R. Brown, J. M. Amini, D. Leibfried, D. J. Wineland: ''Microwave quantum logic gates for trapped ions.'' In: ''Nature.'' 476, 2011, S.&nbsp;181–184, [[doi:10.1038/nature10290]]</ref>

Am 2. Januar 2014 meldete die ''[[Washington Post]]'' unter Berufung auf Dokumente des Whistleblowers [[Edward Snowden]], dass die [[National Security Agency]] (NSA) der USA an der Entwicklung eines „kryptologisch nützlichen“ Quantencomputers arbeitet.<ref>[https://www.washingtonpost.com/world/national-security/nsa-seeks-to-build-quantum-computer-that-could-crack-most-types-of-encryption/2014/01/02/8fff297e-7195-11e3-8def-a33011492df2_story.html?hpid=z1 ''NSA seeks to build quantum computer that could crack most types of encryption''.] washingtonpost.com, 3. Januar 2014</ref>

[[IBM]] ermöglicht seit 2015 den Online-Zugriff auf einen supraleiterbasierten Quantenprozessor. Zunächst standen 5 Qubits zur Verfügung, seit November 2017 sind es 20. Die Website umfasst einen Editor, mit dem Programme für den Quantencomputer geschrieben werden können, sowie ein [[Software Development Kit|SDK]] und interaktive Anleitungen.<ref>{{Internetquelle |url=https://www.nature.com/news/ibm-s-quantum-cloud-computer-goes-commercial-1.21585 |titel=IBM's quantum cloud computer goes commercial |autor=Davide Castelvecchi |datum=2017-03-06 |werk=Nature |zugriff=2018-01-16 |sprache=en}}</ref><ref>{{Internetquelle |titel=IBM unveils its most powerful quantum processor yet |url= https://www.engadget.com/2017/05/17/ibm-quantum-q-experience-qubits-most-powerful-processor-yet/ |werk=engadget.com |datum=2017-05-17 |autor=Andrew Dalton |zugriff=2018-01-18 |sprache=en}}</ref><ref>{{Internetquelle |url=https://www.technologyreview.com/s/609451/ibm-raises-the-bar-with-a-50-qubit-quantum-computer/ |titel=IBM Raises the Bar with a 50-Qubit Quantum Computer |autor=Will Knight |datum=2017-11-10 |werk=MIT Technology Review |sprache=en |zugriff=2018-01-16}}</ref> Bis November 2017 wurden über 35 wissenschaftliche Publikationen veröffentlicht, die den IBM-Computer ''Q Experience'' verwendet haben.<ref name="Gil2017">{{Internetquelle |url=https://www.ibm.com/blogs/research/2017/11/the-future-is-quantum/ |autor=Dario Gil |werk=ibm.com |titel=The future is quantum |datum=2017-11-10 |zugriff=2018-01-16 |sprache=en}}</ref> Über die Cloud bietet IBM auch Zugriff auf die 50-Qubit-Maschine in ihrem Labor an. Der Quantenzustand dieses Systems wird für 90 Mikrosekunden gehalten, was Ende 2017 ein Rekord war. Bei der Technik für effiziente Simulation von Quantencomputern auf klassischen Hochleistungsrechnern kündigte IBM 2017 an, die 49-Qubit-Grenze erreicht zu haben.<ref>[https://arxiv.org/abs/1710.05867 Edwin Pednault u.&nbsp;a., Breaking the 49-Qubit Barrier in the Simulation of Quantum Circuits], Arxiv 2017</ref><ref>[https://www.ibm.com/blogs/research/2017/10/quantum-computing-barrier/ Edwin Pednault, Quantum Computing: Breaking Through the 49 Qubit Simulation Barrier], IBM, 17. Oktober 2017</ref>

Außer bei IBM entwickeln (Stand 2018) viele große Computerfirmen sogenannte Quantencomputer bzw. deren Technologie, so [[Google]], [[Microsoft]], [[Intel]] und Startups wie Rigetti in San Francisco. Google stellte 2018 seinen neuen Quantenprozessor ''Bristlecone'' mit 72 Qubits (skaliert von vorher 9 Qubits) und niedriger Fehlerrate für logische Operationen und Auslesen vor.<ref>[https://ai.googleblog.com/2018/03/a-preview-of-bristlecone-googles-new.html A Preview of Bristlecone, Google’s New Quantum Processor], AI Googleblog, 5. März 2018</ref> Er basiert auch auf Supraleitern und dient hauptsächlich der Erforschung der Technologie und eventuell in naher Zukunft dem Nachweis von ''Quantum Supremacy'' ([[John Preskill]] 2012),<ref>[https://www.nature.com/news/race-for-quantum-supremacy-hits-theoretical-quagmire-1.22993 Philip Ball, Race for quantum supremacy hits theoretical quagmire], Nature News, 13. November 2017</ref> also eines Problems, bei dem der Quantencomputer einem klassischen Supercomputer überlegen ist und dessen Lösung als nächster großer Schritt auf dem Weg zum Quantencomputer gilt (Stand August 2018). Google schätzt wie auch andere Computerfirmen, dass zur Demonstration von ''Quantum Supremacy'' mindestens 49 Qubits, eine Schaltkreistiefe von über 40 und eine Fehlerrate unter einem halben Prozent erforderlich sind. Die Anzahl der Qubits alleine ist nicht entscheidend, sondern zum Beispiel auch die Fehlerrate und die Tiefe des Schaltkreises, das heißt die Anzahl der Gatter (logischen Operationen), die in den Qubits implementiert werden können, bevor die Kohärenz aufgrund zu hoher Fehlerrate zerstört wird. Vor Bristlecone erreichte Google eine Fehlerrate von rund 1 Prozent für Auslesen und für die logischen Operationen 0,1 Prozent für Gatter eines einzelnen Qubits und 0,6 Prozent für Zwei-Qubit-Gatter.<ref>[https://techcrunch.com/2018/03/05/googles-new-bristlecone-processor-brings-it-one-step-closer-to-quantum-supremacy/?guccounter=1 Frederic Lardinois, Google’s new Bristlecone processor brings it one step closer to quantum supremacy], Techcrunch, 5. März 2018</ref> Ein kommerziell nutzbarer Quantencomputer liegt nach Google bei rund 1 Million Qubits.

Microsoft konzentriert sich (Stand 2018) auf theoretische Arbeiten über die Fehlerkorrektur mit Hilfe topologischer Quantencomputer (ein Konzept, das [[Alexei Jurjewitsch Kitajew]] 1997 einführte) unter Leitung des Mathematikers [[Michael Freedman]] und entwickelte einen Simulator, mit dem Quantencomputer auf klassischen Computern simuliert werden können, und  Software für Quantencomputer. Sie haben ein eigenes Quantencomputerlabor (Station Q) in Santa Barbara.<ref>[https://techcrunch.com/2017/09/25/microsoft-places-its-bets-on-quantum-computing/ Frederic Lardinois, Microsoft places its bets on quantum computing], Techcrunch, 26. September 2017</ref>

== Literatur ==
* D. Bruß: ''Quanteninformation'' Fischer Taschenbuch Verlag, Frankfurt am Main 2015, ISBN 978-3-596-30422-6.
* M. Homeister: ''Quantum Computing verstehen: Grundlagen, Anwendungen, Perspektiven'' Springer/Vieweg, Wiesbaden 2015, vierte Auflage, ISBN 978-3-658-10454-2.
* B. Lenze: ''Mathematik und Quantum Computing'' Logos Verlag, Berlin 2018, ISBN 978-3-8325-4716-5.
* R.J. Lipton, K.W. Regan: ''Quantum Algorithms via Linear Algebra: A Primer'' MIT Press, Cambridge MA 2014, ISBN 978-0-262-02839-4.
* C.J. Meier: ''Eine kurze Geschichte des Quantencomputers.'' Verlag Heinz Heise, Hannover 2015, ISBN 978-3-944099-06-4.
* A. Montanaro: ''Quantum Algorithms'', npj Quantum Information, Band 2, 2016, S. 15023, [https://arxiv.org/abs/1511.04206 Arxiv]
* M.A. Nielsen, I.L. Chuang: ''Quantum Computation and Quantum Information.'' Cambridge University Press, Cambridge MA 2000, ISBN 0-521-63503-9.
* W. Scherer: ''Mathematik der Quanteninformatik'' Springer-Verlag, Berlin-Heidelberg 2016, ISBN 978-3-662-49079-2.
* J. Stolze, D. Suter: ''Quantum Computing: A Short Course from Theory to Experiment.'', Wiley-VCH, Weinheim 2004, ISBN 3-527-40787-1.
* [http://www.xplora.org/downloads/Knoppix/BMBF/Einsteins_unverhofftes_Erbe.pdf ''Einsteins unverhofftes Erbe. Quanteninformationstechnologie''.] (PDF; 1,6&nbsp;MB) Broschüre des Bundesministeriums für Bildung und Forschung, 2005.
* [[Neil Gershenfeld|Gershenfeld, Neil]], and Isaac L. Chuang. "[http://cba.mit.edu/docs/papers/98.06.sciqc.pdf Quantum computing with molecules.]" Scientific American 278.6 (1998): 66-71.

== Weblinks ==
{{Commonscat|Quantum computing|Quantencomputer}}
{{Wiktionary}}
* {{SEP|http://plato.stanford.edu/entries/qt-quantcomp|Quantum Computing}}
*[https://qt.eu/news/quantum-technology-roadmap/ Quantum Technology Roadmap], EU, 2018

== Einzelnachweise und Fußnoten ==
<references />

{{Normdaten|TYP=s|GND=4533372-5}}

[[Kategorie:Computer]]
[[Kategorie:Quanteninformatik]]
